### ISSUE TITLE
Lazy update

### ISSUE THREAD

**Issue by pkpio** [azizulhakim/beagleusb#4]
Can you give additional info on the lazy update you mentioned in your [Week #5 update](https://groups.google.com/forum/#!topic/beagleboard-gsoc/rc0CvvjCM4o) ?

**Comment by azizulhakim** [comment]
In bone we have limited cache, so there are too many page faults. Though bone usb transfer speed is same to my laptop, still due to high page fault I've to send a lot of data. For example in laptop I've around 5000 page fault for a 7 second video, whereas in bone it is more than 20,000 page fault. So it takes more time to send the data which means you'll see a video playback time to be around 25 seconds whereas actual playback time is only 7 seconds.

Let's assume I need 10ms to send one page over USB. Now by the time I'm done with this transfer, this same page is going to be updated 5 times. So after 10 ms I've 5 new page to transfer again. So the idea is to send only the most recent update, not all of them. This is lazy update. When I've a new page, I'll wait for a little with a hope that this page is going to be updated again. Off course we'll lose video quality a little by doing this, but given the situation we have to compromise a little. It seems reasonable to me. 

Any other suggestion is also welcome.

**Comment by pkpio** [comment]
@azizulhakim , I should have been more specific when I said more details.

I was asking for more details related to implementation. Like what and how much additional data you would be saving for this and some specifics of tentative implementation plans.

I really think Lazy update would be a good way to tackle the issue. Good job on that :+1:

**Comment by azizulhakim** [comment]
@praveendath92 My plan is very simple. Just keep  an indexed array where each index represents corresponding vertical page index. This array value will represent which page is dirty and needs to be updated.

There'll be a kernel thread which will just traverse through the array and find out the pages that needs to be updated. This way it doesn't need to send all the updates on a single page. Only the most recent one is sent.

**Comment by azizulhakim** [comment]
fix  71fe580bb65602404d6b22ecb6fff2cedf0e1c23
